import pandas as pd
from datetime import date,timedelta
import matplotlib.pyplot as plt

# sym = input("Enter a stock symbol ").upper()
# df = pd.read_csv("C:\Users\DELL\OneDrive\Desktop\\finpulse-lite\data")

#Storing the data from CSV files and plotting closing price vs date and MA vs date on same chart
reliance = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\Reliance.csv",usecols=["Close","Date"])
reliance["Date"] = pd.to_datetime(reliance["Date"])
reliance = reliance.set_index("Date")
plt.plot(reliance,label = "Closing Price")
plt.plot(reliance["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(reliance["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-Reliance")
plt.legend()
plt.show()

TCS = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\TCS.csv",usecols=["Close","Date"])
TCS["Date"] = pd.to_datetime(TCS["Date"])
TCS = TCS.set_index("Date")
plt.plot(TCS,label = "Closing Price")
plt.plot(TCS["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(TCS["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-TCS")
plt.legend()
plt.show()

INFY = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\INFY.csv",usecols=["Close","Date"])
INFY["Date"] = pd.to_datetime(INFY["Date"])
INFY = INFY.set_index("Date")
plt.plot(INFY,label = "Closing Price")
plt.plot(INFY["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(INFY["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-INFY")
plt.legend()
plt.show()

HDFCBANK = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\HDFCBANK.csv",usecols=["Close","Date"])
HDFCBANK["Date"] = pd.to_datetime(HDFCBANK["Date"])
HDFCBANK = HDFCBANK.set_index("Date")
plt.plot(HDFCBANK,label = "Closing Price")
plt.plot(HDFCBANK["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(HDFCBANK["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-HDFCBANK")
plt.legend()
plt.show()

ICICIBANK = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\ICICIBANK.csv",usecols=["Close","Date"])
ICICIBANK["Date"] = pd.to_datetime(ICICIBANK["Date"])
ICICIBANK = ICICIBANK.set_index("Date")
plt.plot(ICICIBANK,label = "Closing Price")
plt.plot(ICICIBANK["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(ICICIBANK["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-ICICIBANK")
plt.legend()
plt.show()

SBIN = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\SBIN.csv",usecols=["Close","Date"])
SBIN["Date"] = pd.to_datetime(SBIN["Date"])
SBIN = SBIN.set_index("Date")
plt.plot(SBIN,label = "Closing Price")
plt.plot(SBIN["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(SBIN["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-SBIN")
plt.legend()
plt.show()

ITC = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\ITC.csv",usecols=["Close","Date"])
ITC["Date"] = pd.to_datetime(ITC["Date"])
ITC = ITC.set_index("Date")
plt.plot(ITC,label = "Closing Price")
plt.plot(ITC["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(ITC["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-ITC")
plt.legend()
plt.show()

LT = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\LT.csv",usecols=["Close","Date"])
LT["Date"] = pd.to_datetime(LT["Date"])
LT = LT.set_index("Date")
plt.plot(LT,label = "Closing Price")
plt.plot(LT["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(LT["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-LT")
plt.legend()
plt.show()

HINDUNILVR = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\HINDUNILVR.csv",usecols=["Close","Date"])
HINDUNILVR["Date"] = pd.to_datetime(HINDUNILVR["Date"])
HINDUNILVR = HINDUNILVR.set_index("Date")
plt.plot(HINDUNILVR,label = "Closing Price")
plt.plot(HINDUNILVR["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(HINDUNILVR["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-HINDUNILVR")
plt.legend()
plt.show()

KOTAKBANK = pd.read_csv("C:\\Users\DELL\OneDrive\Desktop\\finpulse-lite\data\KOTAKBANK.csv",usecols=["Close","Date"])
KOTAKBANK["Date"] = pd.to_datetime(KOTAKBANK["Date"])
KOTAKBANK = KOTAKBANK.set_index("Date")
plt.plot(KOTAKBANK,label = "Closing Price")
plt.plot(KOTAKBANK["Close"].rolling(window="50D").mean(),label = "50 Day Moving Average")
plt.plot(KOTAKBANK["Close"].rolling(window="200D").mean(),label="200 Day Moving Average")
plt.xlim(left=date.today()-timedelta(days=365*5),right = date.today())
plt.xlabel("Date")
plt.ylabel("Price")
plt.title("Moving Averages-KOTAKBANK")
plt.legend()
plt.show()